version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  check_vulnerabilities:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-deployment
    steps:
      - run: npm install
      - run: npm audit
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release
workflows:
  version: 2
  build:
    jobs:
      - check_vulnerabilities
  build_and_release:
    jobs:
      - check_vulnerabilities:
          filters:
            branches:
              only:
                - master
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - check_vulnerabilities
