version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  check_vulnerabilities:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-deployment
    steps:
      - run: npm audit
workflows:
  test_build_deploy:
    jobs:
      - check_vulnerabilities
