version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  check_vulnerabilities:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-deployment
    steps:
      - run: npm install
      - run: npm audit
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - check_vulnerabilities
  test_and_release:
    jobs:
      - check_vulnerabilities
      - release:
          requires:
            - check_vulnerabilities
